Repository apluslms/a-plus, pull requests merged in 2020-06, with the labels that each got.

#564 Improve extra login options on login page
  aplus/settings.py
  locale/fi/LC_MESSAGES/django.po
  userprofile/static/userprofile/extra_logins.js
  userprofile/static/userprofile/login.css
  userprofile/templates/userprofile/login.html
  userprofile/views.py
Labels: area: user interface, priority: medium, type: refactoring

#547 Implement a consistent focus state
  assets/css/main.css
  assets/js/focus-visible-polyfill.js
  assets/js/focus-visible-polyfill.min.js
  assets/js/focus-visible-polyfill.min.js.map
  templates/base.html
Labels: area: accessibility, priority: medium, type: feature

#560 Increase usability of front page with instance names, longer course visibility and sectioning
  assets/css/main.css
  course/templates/course/_course_cards.html
  course/templates/course/index.html
  course/views.py
  locale/fi/LC_MESSAGES/django.po
  selenium_test/test/locators.py
Labels: area: user interface, type: feature, type: refactoring
